[package]
name = "indi_exporter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indi = "3.0.0"
prometheus = "0.13.3"
prometheus_exporter = "0.8.5"
